
import { CEFRLevel, LevelCriteria, Sentence } from './types';

export const LEVEL_CRITERIA: Record<CEFRLevel, LevelCriteria> = {
  [CEFRLevel.A1]: { min: 0, max: 20, label: "Beginner", description: "Can understand and use familiar everyday expressions and very basic phrases.", color: "bg-red-500" },
  [CEFRLevel.A2]: { min: 21, max: 40, label: "Elementary", description: "Can understand sentences and frequently used expressions related to areas of most immediate relevance.", color: "bg-orange-500" },
  [CEFRLevel.B1]: { min: 41, max: 60, label: "Intermediate", description: "Can deal with most situations likely to arise whilst travelling in an area where the language is spoken.", color: "bg-yellow-500" },
  [CEFRLevel.B2]: { min: 61, max: 80, label: "Upper Intermediate", description: "Can interact with a degree of fluency and spontaneity that makes regular interaction with native speakers quite possible.", color: "bg-emerald-500" },
  [CEFRLevel.C1]: { min: 81, max: 95, label: "Advanced", description: "Can express him/herself fluently and spontaneously without much obvious searching for expressions.", color: "bg-blue-600" },
  [CEFRLevel.C2]: { min: 96, max: 100, label: "Proficiency", description: "Can understand with ease virtually everything heard or read.", color: "bg-purple-600" },
};

export const TEST_SENTENCES: Sentence[] = [
  { id: 1, text: "Hello, how are you doing today?", difficulty: 1 },
  { id: 2, text: "I would like to order a cup of coffee.", difficulty: 1 },
  { id: 3, text: "The weather is very nice outside.", difficulty: 1 },
  { id: 4, text: "Where is the nearest subway station?", difficulty: 1 },
  { id: 5, text: "My favorite hobby is reading books.", difficulty: 1 },
  { id: 6, text: "Could you please tell me the time?", difficulty: 2 },
  { id: 7, text: "I enjoy traveling to new countries every summer.", difficulty: 2 },
  { id: 8, text: "Learning a new language opens up many opportunities.", difficulty: 2 },
  { id: 9, text: "She decided to study architecture at the university.", difficulty: 2 },
  { id: 10, text: "Waiters usually expect a tip in some cultures.", difficulty: 2 },
  { id: 11, text: "Artificial intelligence is changing the way we work.", difficulty: 3 },
  { id: 12, text: "The presentation was informative and well-organized.", difficulty: 3 },
  { id: 13, text: "Global warming is a significant threat to our planet.", difficulty: 3 },
  { id: 14, text: "I appreciate your assistance in this complex matter.", difficulty: 3 },
  { id: 15, text: "Success requires persistent effort and dedication.", difficulty: 3 },
  { id: 16, text: "Economic fluctuations can impact consumer spending habits.", difficulty: 4 },
  { id: 17, text: "The researcher conducted a thorough investigation into the phenomenon.", difficulty: 4 },
  { id: 18, text: "Balancing professional responsibilities with personal life is challenging.", difficulty: 4 },
  { id: 19, text: "Diverse perspectives contribute to more innovative solutions.", difficulty: 4 },
  { id: 20, text: "The legislation aims to improve public health standards significantly.", difficulty: 4 },
  { id: 21, text: "Notwithstanding the obstacles, the project was completed on schedule.", difficulty: 5 },
  { id: 22, text: "The intricate details of the masterpiece were truly breathtaking.", difficulty: 5 },
  { id: 23, text: "Meticulous planning is essential for large-scale infrastructure projects.", difficulty: 5 },
  { id: 24, text: "He articulated his arguments with remarkable clarity and conviction.", difficulty: 5 },
  { id: 25, text: "Technological advancements have revolutionized modern communications.", difficulty: 5 },
  // ... adding more to reach 50 for a full test
  { id: 26, text: "A journey of a thousand miles begins with a single step.", difficulty: 1 },
  { id: 27, text: "Consistency is the key to mastering any skill.", difficulty: 2 },
  { id: 28, text: "The cat sat on the mat looking out the window.", difficulty: 1 },
  { id: 29, text: "Breakfast is considered the most important meal of the day.", difficulty: 2 },
  { id: 30, text: "Urbanization has led to the rapid growth of megacities.", difficulty: 3 },
  { id: 31, text: "Sustainable development ensures a better future for coming generations.", difficulty: 3 },
  { id: 32, text: "The orchestra performed a magnificent symphony last night.", difficulty: 4 },
  { id: 33, text: "Philosophical inquiries often lead to profound insights about life.", difficulty: 5 },
  { id: 34, text: "It is crucial to maintain a healthy work-life balance.", difficulty: 3 },
  { id: 35, text: "Scientific discoveries have significantly extended human life expectancy.", difficulty: 4 },
  { id: 36, text: "I was wondering if you could help me with this heavy luggage.", difficulty: 2 },
  { id: 37, text: "Exploring the depths of the ocean reveals a mysterious world.", difficulty: 4 },
  { id: 38, text: "Cultural exchange fosters mutual understanding and respect.", difficulty: 3 },
  { id: 39, text: "The entrepreneur launched a groundbreaking startup in the valley.", difficulty: 4 },
  { id: 40, text: "Effective communication is fundamental in all interpersonal relationships.", difficulty: 3 },
  { id: 41, text: "He was fascinated by the intricate mechanisms of the ancient clock.", difficulty: 4 },
  { id: 42, text: "The mountain peak was covered in a thick blanket of pristine snow.", difficulty: 3 },
  { id: 43, text: "Digital transformation requires organizations to adapt their strategies.", difficulty: 4 },
  { id: 44, text: "Laughter is often said to be the best medicine for stress.", difficulty: 2 },
  { id: 45, text: "The astronaut gazed at the earth from the space station.", difficulty: 3 },
  { id: 46, text: "Biodiversity is essential for the stability of our ecosystem.", difficulty: 4 },
  { id: 47, text: "Her performance was met with a standing ovation from the audience.", difficulty: 3 },
  { id: 48, text: "Cognitive development in children is influenced by various factors.", difficulty: 5 },
  { id: 49, text: "The historical archive contains rare documents from the middle ages.", difficulty: 4 },
  { id: 50, text: "Innovation is the byproduct of creative thinking and experimentation.", difficulty: 5 },
];
